const char INDEX_HTML[] =
"<!DOCTYPE HTML>"
"<html>"
"<head>"
"<meta content=\"text/html; charset=ISO-8859-1\""
" http-equiv=\"content-type\">"
"<meta name = \"viewport\" content = \"width = device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable=0\">"
"<title>ESP8266 Web Form Demo</title>"
"<style>"
"\"body { background-color: #808080; font-family: Arial, Helvetica, Sans-Serif; Color: #87CEFA; text-align:center;}\""
"</style>"
"</head>"
"<body style=\"background-color:powderblue;\">"
"<h3>NIMESH INNOVATIONS</h3>"
"<center>&</center>"
"<h1> Suthar Electronics</h1><br><br>"
"<h3>Enter your WiFi credentials</h3>"
"<form action=\"/\" method=\"post\">"
"<p>"
//"<label>SSID:&nbsp;</label>"
//"<input maxlength=\"30\" name=\"ssid\"><br>"
//"<label>Key:&nbsp;&nbsp;&nbsp;&nbsp;</label><input maxlength=\"30\" name=\"password\"><br>"
//"<input type=\"submit\" value=\"Save\">"
//"<br><br>"

"  <label for=\"fname\">Enter SSID:</label>"
"  <input type=\"text\" maxlength=\"30\" id=\"fname\" name=\"ssid\"><br><br>"
"  <label for=\"lname\">Enter PASS:</label>"
"  <input type=\"text\" maxlength=\"30\" id=\"lname\" name=\"password\"><br><br>"
"  <input type=\"submit\" value=\"Save\">"


"</p>"
"</form>"
"</body>"
"</html>";
